### ISSUE TITLE
Load patch from memory

### ISSUE THREAD

**Issue by steadysupply** [libpd/libpd#326] opened 2021-03-09 17:30 UTC
I would like to use `libpd` to load a Pd patch from memory rather than reading from the filesystem.

Using the `-i` flag, [`xxd`](https://linux.die.net/man/1/xxd) can dump file contents in C include format (as an array of `char`) which is usable by eg. [`stb_image.h`](https://github.com/nothings/stb/blob/master/stb_image.h#L392) meaning that I can embed image files in a shipped binary.

Would something similar be possible using `libpd`?

**Comment by steadysupply** [comment] 2021-03-09 17:40
I suppose a workaround might be to write embedded data out to a temporary file and pass the its path to `libpd`.

**Comment by danomatika** [comment] 2021-03-09 19:15
Duplicate of #300. Please move further discussion there.

**Closed by danomatika** 2021-03-09 19:15 UTC
