### ISSUE TITLE
Remove URL from info

### ISSUE THREAD

**Issue by residuum** [libpd/libpd#348] opened 2022-04-07 16:13 UTC
Since libpd.cc is not associated with the project anymore, please remove the URL from the info.
![Screenshot](https://user-images.githubusercontent.com/136216/162249165-7fa11404-8207-451c-b308-cb84d262c46d.png)

**Comment by danomatika** [comment] 2022-04-07 18:48
Duplicate of #301.

**Closed by danomatika** 2022-04-07 18:48 UTC
