### ISSUE TITLE
`libpd_start_gui` fails on Windows

### ISSUE THREAD

**Issue by alisomay** [libpd/libpd#352] opened 2022-04-18 17:20 UTC
Running `libpd_start_gui` in 64 bit Intel Windows 10 yields the following error.
```
localhost not found (inet protocol not installed?)
Either the application has not called WSAStartup, or WSAStartup failed
```
I don't plan to debug this since I can't imagine a case yet why a user would need this feature yet and also not very experienced in Windows platforms.
Although I think it is worth to note it here for some other people who might need this functionality.

I've tested it in a Github Action runner and an AWS instance through remote desktop. 
If a reader of this can make it work, I'd love to hear how to.

**Comment by danomatika** [comment] 2022-04-18 17:44
libpd just calls a pd core function which does this, so it's probably better to open an issue upstream on the pure-data repo.

**Comment by danomatika** [comment] 2022-04-18 17:45
Paging @Spacechild1

**Comment by alisomay** [comment] 2022-04-18 19:49
Issue opened in upstream.

https://github.com/pure-data/pure-data/issues/1630

**Comment by Spacechild1** [comment] 2022-04-18 21:20
The error message actually tells the problem:
> Either the application has not called WSAStartup

The problem is that libpd does not call `socket_init()` - which internally calls `WSAStartup`.

Two solutions:
1. call `socket_init` in `libpd_init`
2. move the `socket_init()` call in `sys_main` into `pd_init`, so that it will be called implicitly by `libpd_init`

**Comment by alisomay** [comment] 2022-04-18 21:44
Thank you @Spacechild1 not it seems clear, I can make a PR in the coming days to implement it as you specified. 
On the other hand if one of you would like to go first I don't mind.

**Comment by Spacechild1** [comment] 2022-04-20 22:05
I think there are arguments for both solutions. Just pick the one that is more convenient :-)

**Comment by danomatika** [comment] 2022-04-26 02:54
Ok, I went with the libpd route for now. Please test the `bugfix/start-gui-windows` branch.

**Comment by danomatika** [comment] 2022-04-30 07:45
If you confirm the bugfix works, I can merge the branch and we can close the issue.

**Comment by alisomay** [comment] 2022-05-02 09:41
Sorry I have missed this, I'll check today after work.

**Comment by alisomay** [comment] 2022-05-04 18:47
There was an unusual business, sorry for delaying this.
I now tested it and I get, (AWS Instance)
```sh
spawnl: No such file or directory
C:\Users\Administrator\libpd-rs\tests\pd_binary\win\Pd-0.52-2\bin\wish85.exe: couldn't load TCL
```

**Comment by danomatika** [comment] 2022-05-09 15:31
@Spacechild1 Any thoughts on this? @alisomay What is the path you are giving `libpd_start_gui()`?

**Comment by alisomay** [comment] 2022-05-09 22:44
`C:\Program Files\Pd` or `C:\Users\Administrator\libpd-rs\tests\pd_binary\win\Pd-0.52-2` which are both valid installations.

**Comment by Spacechild1** [comment] 2022-05-09 23:21
@alisomay Can you list the content of the `Pd` resp. `Pd-0.52-2` folder?

**Comment by alisomay** [comment] 2022-05-10 07:33
The other one (`C:\Program Files\Pd`) is just an ordinary default windows installation of Pd. 
The directory contents are the same as the included installation folder in the link which I have shared with you.

**Comment by Spacechild1** [comment] 2022-05-10 09:20
Both folders contain `wish86.exe`, but you attempt to start `wish85.exe` (= the default). You have to set the `WISH` definition to `wish86.exe`. With the autotools build system, you can do this with `--with-wish=wish86.exe`.

**Comment by alisomay** [comment] 2022-05-10 11:20
This looks promising. I'll try and report soon.

**Comment by danomatika** [comment] 2022-05-10 17:35
Also, Ali you can try setting the WISH define to wish86.exe. This is what the —with-wish configure option sets. Actually, I can’t remember if it’s WISH or maybe WISHAPP.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by alisomay** [comment] 2022-06-15 21:10
@danomatika, @Spacechild1 

I just had time to test defining `WISH`.
It works fine!

I found the source here if anybody reads this and get interested about where it is defined.
https://github.dev/pure-data/pure-data/tree/18c9695ba4de543c51c2c013b45b99b8f1c35a19

Thanks for your help, I think we can consider this resolved.
@danomatika I think you may merge [the branch](https://github.com/libpd/libpd/tree/bugfix/start-gui-windows)
whenever you wish and close the issue.

**Comment by danomatika** [comment] 2022-06-15 21:24
Branch is merged.

**Closed by danomatika** 2022-06-15 21:24 UTC
Labels: upstream-bug

**Comment by danomatika** [comment] 2022-10-11 07:37
Hrmm then we need to change the default wish version in the pure-data repo. I believe it’s in the platform section of configure.ac

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com
