### ISSUE TITLE
Unity standalone player crashes with access violation while unity editor works fine (windows 64 bit)

### ISSUE THREAD

**Issue by Nagasaki45** [libpd/libpd#234] opened 2018-03-23 13:11 UTC
Hi,

First, thanks a lot for developing and maintaining this project!

I have a [simple testing project](https://github.com/Nagasaki45/unipd) that uses libpd in unity, without any wrapper except for the one provided by libpd and a few lines of code [here](https://github.com/Nagasaki45/unipd/blob/master/Assets/PatchPlayer.cs). Inside the unity editor everything works as expected. When I build the project for windows 64 bit the player crashes when attempting to call libpd. I built the dll both with `make csharplib` and with the `.bat` file and got the same result. The dll from NuGet crashes in the same way. Building for linux 64 bit works fine. [Here's my unity bug report](https://fogbugz.unity3d.com/default.asp?1016412_2944f08pde95fvnl) (very similar to this one). I assumed that the problem is on their side because everything works in the unity editor.

# Steps to reproduce

- Follow the instructions in the README to compile for windows 64 bit.
- Copy the binaries to [the unity testing project](https://github.com/Nagasaki45/unipd)  `Assets/Plugins/` directory (or investigate the ones I compiled).
- Build the unity project for windows 64 bit.
- Run the built application, and it will crash.

# Software versions

- Windows 10 Home, version 1709, OS build 16299.309.
- Unity 2017.3.0p2 Personal (64bit).
- MSYS2 64bit 20161025.
- libpd 0.10.0 (with correct Pd version and following the appropriate README file).

Any help will be much appreciated!

Thanks,
Tom

**Comment by antpb** [comment] 2018-04-08 13:29
I'm having the exact same issue. Works in editor, crashes in build. I'm wondering if I should yank pd v 0.47-1, replace it in the current repo, and rebuild. I tried that method by replacing the pure-data directory using the one from a few months ago but had no luck. Might need an older version?

If you figure this one out @Nagasaki45 I'd be very happy to know what you find! I'll continue digging...

**Comment by antpb** [comment] 2018-04-08 13:35
Also, @Nagasaki45 in this issue: https://github.com/djkoloski/libpd64/issues/4

@djkoloski provided some warnings that may be very helpful in pinpointing the problem. I'm hoping to start digging through them soon: 

```
pure-data/src/g_canvas.c:1391:5: warning: implicit declaration of function 'u8_utf8toucs2' [-Wimplicit-function-declaration]
     u8_utf8toucs2(ucs2path, MAXPDSTRING, pathbuf, MAXPDSTRING-1);
pure-data/src/g_canvas.c:1392:19: warning: implicit declaration of function '_waccess' [-Wimplicit-function-declaration]
     return (0 ==  _waccess(ucs2path, 0));
pure-data/src/s_main.c: In function 'sys_main':
pure-data/src/s_main.c:337:20: warning: '__p__fmode' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
         extern int _fmode;
pure-data/extra/sigmund~/sigmund~.c: In function 'sigmund_getpitch.isra.7':
pure-data/extra/sigmund~/sigmund~.c:385:14: warning: argument 1 value '18446744073709551424' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
     t_float *weights =  (t_float *)alloca(sizeof(t_float) * npit);
```

**Comment by antpb** [comment] 2018-04-15 20:34
Just an update from my end. Found the issue to be something that changed in the way that Unity handle's .dll files. The changed happened between 2017.1 and 2017.2. All version 2017.2 and up will see this same issue. I'm still trying to dig through the changes to see what could be happening in Unity. Sadly nothing new yet. 

Here's the changelog I'm trying to reverse. It hasn't been going so well :/ 
[https://unity3d.com/unity/whats-new/unity-2017.2.0](https://unity3d.com/unity/whats-new/unity-2017.2.0)

**Comment by Nagasaki45** [comment] 2018-04-15 22:03
Hi @antpb. Thanks for putting the efforts into this!

I ended up "connecting" unity and Pd by networking. In my project I analyse audio input with Pd and need the results in unity, so I just have the patch open in Pd in the background and sending messages over TCP to unity. Not ideal but working.

Let me know if there's anything I can help with.
Good luck!

**Comment by ATHellboy** [comment] 2018-05-01 06:39
Do you find a solution about standalone Windows 64bit build ?

**Comment by antpb** [comment] 2018-05-01 16:42
@ATHellboy no luck still :/ I shelved my efforts in fixing this to focus on making progress in building out my game. I'll have to circle around back to this build error when I'm done building my demo. I've tested the build in 2018.1 and still no luck. Something changed in the way they are handling dll

**Comment by ATHellboy** [comment] 2018-05-05 03:07
@antpb  Can you build standalone windows 64bit version by any previous version of Unity ?
And is this problem caused by Unity or can be fixed by libpd ?

**Comment by ATHellboy** [comment] 2018-05-05 04:31
This is a error on x86_64 build:

```
ArgumentException: The specified path is not of a legal form (empty).
  at System.IO.Path.InsecureGetFullPath (System.String path) [0x001d2] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Path.cs:380 
  at System.IO.Path.GetFullPath (System.String path) [0x00000] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Path.cs:289 
  at Magicolo.AudioTools.PureDataSequenceManager.SetContainerPath () [0x00036] in F:\Project\uPD\Assets\Magicolo\AudioTools\PureData\PureDataSequenceManager.cs:157 
  at Magicolo.AudioTools.PureDataSequenceManager.UpdateSequenceContainer () [0x00002] in F:\Project\uPD\Assets\Magicolo\AudioTools\PureData\PureDataSequenceManager.cs:61 
  at Magicolo.AudioTools.MusicGenerator.SequenceInitialization (Int32 index) [0x00506] in F:\Project\uPD\Assets\Scripts\MusicGenerator.cs:227 
  at Magicolo.AudioTools.MusicGenerator.Start () [0x00003] in F:\Project\uPD\Assets\Scripts\MusicGenerator.cs:24 
 
(Filename: /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Path.cs Line: 380)
```

**Comment by ATHellboy** [comment] 2018-05-07 05:13
I've solved it. This error just because of one of my pd directory.

**Comment by ATHellboy** [comment] 2018-05-07 08:25
Have you built development build of your game ? What are the errors in the console ?
I used uPD by some additional features by myself and the problem was in the part which try to find the path of one of its pd's file. Also I built it by x86_64 architecture on Unity 2018.1

**Comment by antpb** [comment] 2018-05-07 15:07
@ATHellboy  I also built mine in 2018.1 and it still fails. I did notice as you mentioned that the path to the pure data file looks lomething like file missing `StreamingAssets/atches/main.pd` where it is missing the `P` how did you resolve the path in the script? I've reset it using the Editor tool but it still has the same result. 

Thanks for helping out!

**Comment by ATHellboy** [comment] 2018-05-07 15:18
I think if you change your path to 

> Application.streamingAssetsPath + "atches/main.pd", it will be good enough

**Comment by antpb** [comment] 2018-05-08 03:54
@ATHellboy thanks for that! I changed that path and it seems to have fixed the path issue! However, it is still unable to build. Now it's not even giving me a crash log >__< going to have to keep digging

**Comment by danomatika** [comment] 2018-07-24 23:15
In the end, is this a problem with Unity or the libpd C# wrapper? If Unity, then please close this issue. If C#, then the recent updates for C# which should be merged soon *may* help. None of the libpd developers use Unity, so we are not really going to be much help. I'd prefer to close the issue if you feel the scope is beyond what we can discuss here.

**Comment by ATHellboy** [comment] 2018-07-25 02:57
As I know I think this problem was because of incorrect path for finding patches. Also for 64 bit build need to build by x86_64 architecture in Unity. so I think it is solved.

**Comment by ozansarier** [comment] 2018-07-25 03:46
I was able to compile a dll that works with Unity 2018 by solving all the compiler errors.

**Comment by ozansarier** [comment] 2018-07-25 04:02
(Based on 0.10.0 branch)
https://github.com/ozansarier/libpd/tree/libPdForUnity2018

**Comment by Nagasaki45** [comment] 2018-07-25 10:05
@ozansarier, your [new DLL](https://github.com/Nagasaki45/unipd/pull/1/files) solved the problem in my example project (Unity 2017.3.0p2 Personal 64bit). Thanks for that! I tried to understand how you generated a working DLL, but couldn't. I found [this](https://github.com/ozansarier/libpd/commit/f92951653d7b3e839d3ce4871fb9b7274b3116d8) in your libpd repo. It shows that you use a different version of Pd than 0.47-1. The commit that you use (56d94b) is missing from the official Pd repo. Can make it available online? Maybe by forking Pd and pushing the branch with the fix?

@danomatika, I didn't know if the problem is with libpd or Unity when I opened this ticket. The DLL from @ozansarier suggests that it's at least possible to solve the issue from the libpd side, even if it's just a workaround for a Unity bug. I understand that none of the core libpd devs use Unity, and that you can't help much here. Still, I can't think of a better place to discuss a solution for this problem. Keeping this issue open until we find a proper solution will be much appreciated.

**Comment by danomatika** [comment] 2018-07-25 10:10
@Nagasaki45 The submodule has recently been updated, so the commits should be up to date.

>I was able to compile a dll that works with Unity 2018 by solving all the compiler errors.

@ozansarier It would be nice to know what you needed to do so you/we can apply the appropriate fixes. The ideal situation is to avoid relying on pre-built binaries, where possible (aka reproducible builds).

**Comment by danomatika** [comment] 2018-07-25 11:33
@umlauete Can you check [this](https://github.com/pure-data/pure-data/compare/0.47-1...ozansarier:0.47-1_Unity2018_Fix?expand=1)? It seems like some of the casts should be replaced by PD_LONGINTTYPE. As for the addition of header files, I cannot know that until I get a chance to build it myself.

**Comment by danomatika** [comment] 2019-12-09 14:38
This should be fixed with the last release version of Pd which includes numerous fixes for 64 bit windows. The main thing is to compile with the following for 64 bit longs: 

~~~
-DPD_LONGINTTYPE="long long"'
~~~

I'm going to close this for now. If y'all (re)build and run into this issue again, please reopen or create a new PR.

**Closed by danomatika** 2019-12-09 14:38 UTC
