### ISSUE TITLE
Unable to pair Bluetooth headphones while app is running when using `AVAudioSessionCategoryPlayAndRecord` on iOS

### ISSUE THREAD

**Issue by virusys** [libpd/libpd#249] opened 2018-08-28 17:45 UTC
I am testing on an iPhone 6s using a pair of Mpow Judge Bluetooth headphones (with built-in microphone). This has also been reproduced using Apple's AirPods. 

Here is the code that I am using to setup my `PdAudioController`:

``` objc
self.pdAudio = [[PdAudioController alloc] init];
float samplingRate = 44100;

if ([self DeviceIs6SOrAbove] && ![self isSamplingRateSwitchNeeded]) {
    samplingRate = 48000;
}

[self.pdAudio configurePlaybackWithSampleRate:samplingRate numberChannels:2 inputEnabled:YES mixingEnabled:NO];
// bluetooth support
if (@available(iOS 10.0, *)) {
     [PdAudioController setSessionOptions:AVAudioSessionCategoryOptionAllowBluetoothA2DP];
} else {
    // Fallback on earlier versions
    [PdAudioController setSessionOptions:AVAudioSessionCategoryOptionAllowBluetooth];
}

[self.pdAudio setActive:YES];
```

If the headphones are paired before I launch the app, everything works as intended with no issues. However, if I attempt to pair after the app has launched, my headphones will beep and indicate that they are connected, but the status bar on iOS will remain the same (after flickering briefly) and audio will still be routed out of the default speakers. If I move the app into the background and then back to the foreground again, the headphones will pair as soon as I'm in the Springboard and will continue working normally when I am back in the app. 

What is also strange is that I will receive an `AVAudioSessionRouteChangeNotification` if I unpair the headphones after they are connected, but if I try pairing them again I will get no notifications whatsoever.

I have tried replacing the `configurePlaybackWithSampleRate` line with `configureAmbientWithSampleRate`, and there are no issues paring my BT headphones or receiving route changed notifications (but since I need to use input this is not a suitable workaround). 

I have also tried setting `AVAudioSessionCategoryOptionAllowBluetooth` instead of `AVAudioSessionCategoryOptionAllowBluetoothA2DP` and the headphones are able to pair, but audio becomes choppy as soon as they are. 

If you need any more info please let me know. Thank you!

**Comment by cerupcat** [comment] 2018-10-22 18:41
Did you ever figure this out @virusys?

**Comment by virusys** [comment] 2018-10-23 12:54
@cerupcat Unfortunately no, but I haven't been able to spend too much time on it as of late.

**Comment by danomatika** [comment] 2018-10-24 08:44
This is probably related to #177, Pd's fixed block size and the fact that the audio unit does not due any sample rate conversion. This is definitely a major issue that needs to be solved. I've tried a couple things but I think, now, that we basically just need to use one of the CoreAudio sample rate converter classes. It's on the list for libpd 0.12.0.

**Comment by cerupcat** [comment] 2018-10-24 19:38
Thanks, I'll have to look into it. I previously used `TheAmazingAudioEngine` for the audio units and forwarded them to PD (which I don't think had this issue). Now that I'm integrating abl_link, I'm using the PDAudioController instead `TheAmazingAudioEngine`, and this might be a deal breaker if there are issues with switching between devices with different rates since it's a common case for my app. I'll probably get to spend some more time looking into it in a few days. However, not sure I have the expertise to propose a solution quickly.

**Comment by cerupcat** [comment] 2018-10-24 19:40
@danomatika Do you have an example "CoreAudio sample rate converter class" that you were referring to?

**Comment by danomatika** [comment] 2018-10-24 19:41
The Portaudio sources for the coreadudio backend.

**Comment by virusys** [comment] 2018-10-31 21:32
Hi again, glad to see discussion on this issue. Maybe this information is not that useful if you don't have BT headphones to test with, but the issue is easily reproducable with the `pdtest` sample project found in `samples/objc/ios/pdtest`. The headphones I'm testing with is an Mpow Judge.

**Comment by danomatika** [comment] 2020-01-16 18:13
>If the headphones are paired before I launch the app, everything works as intended with no issues. 

I noticed the same issue while testing PR #283. I think that is just how it is by default. Playback-only categories handle this fine as well as when you launch the app while Bluetooth is active. I think this probably needs some more direct notification handling, as you observed, but I'm feeling it's beyond the scope of the PdAudioUnit at the moment.

I did, however, add convenience properties to help with the category options. Check those out.

One last thing, you are using:

~~~
[PdAudioController setSessionOptions:AVAudioSessionCategoryOptionAllowBluetoothA2DP];
~~~

which sets aka *replaces* the current options, this clearing any other options. When what you probably want is:

~~~
[PdAudioController addSessionOptions:AVAudioSessionCategoryOptionAllowBluetoothA2DP];
~~~

which adds the option without removing anything else.

**Comment by danomatika** [comment] 2020-01-16 18:33
Also, from reading the Apple docs:

AVAudioSessionCategoryOptionAllowBluetooth is 1 channel IO at an 8k sample rate (HFP)

AVAudioSessionCategoryOptionAllowBluetoothA2DP is 2 channel (stereo) output at higher quality

You can specify both options at the same time, but the system will then use HFP if the device supports it before using A2DP. It doesn't seem possible (or at least easy) to read from the Bluetooth mic ay 8k while outputting to the same device over A2DP stereo. This appears to be by design.

I did manage to get the test project to work with my Bluetooth headphones with HFP, but I had to set the PdAudioController sample rate to 8000 explicitly, so it's not quite useful. Honestly, HFP is for VOIP and phone conversations and not quite useful for libpd-based stuff anyway, I imagine.

**Comment by danomatika** [comment] 2020-01-16 20:33
Ok, I did some more experimenting with some Bluetooth headphones + built-in mic. Audio in and out works fine with AVAudioSessionCategoryOptionAllowBluetooth using the PR, but the trick is that the sample rate needs to be a multiple of 8000 when configuring PdAudioController. So 16k, 24k, 48k & 96k are working fine for me. OTOH 44.1k has buffering issues but I'm not sure if I can dig any more into this. I might be easier to suggest a different sample rate.

**Comment by danomatika** [comment] 2020-10-31 03:35
This should be working now. Closed by #283.

**Comment by lwinged** [comment] 2021-06-04 13:35
Hello, 

I’d like to know if you found a solution about this issue :

If the BLE speakers/headphones are paired before I launch the app, everything works as intended with no issues but it doesn’t work while app is running with AVAudioSessionCategoryPlayAndRecord category. 
(it's OK with Playback-only categories)

```
pdAudioController.configurePlayback(withSampleRate: Int32(sampleRate), numberChannels: Int32(inputChannels + outputChannels), inputEnabled: true, mixingEnabled: false)
pdAudioController.allowBluetoothA2DP = true
```

I tried too :
`PdAudioController.addSessionOptions([.allowBluetoothA2DP])
`

I found this :

If the playback is on a speaker which uses A2DP, considering setting the session like this:
```
let audioSession = AVAudioSession.sharedInstance()
do {
      try audioSession.setCategory(AVAudioSessionCategoryPlayAndRecord, 
           mode: AVAudioSessionModeVideoRecording,
           options: [.defaultToSpeaker, .allowAirPlay, .allowBluetoothA2DP])
      try audioSession.setActive(true)
} catch let error {
      print("audioSession properties weren't set!", error)
}
```
 https://stackoverflow.com/questions/50789276/avaudiosession-not-working-on-certain-bluetooth-devices 

Perharps you can allow to set the mode in the public API of PdAudioController. (mode: AVAudioSessionModeVideoRecording)

Do you have any ideas how to fix this issue ? 
Do you think this issue comes from iOS/Apple ?

Thank you :)

**Comment by danomatika** [comment] 2021-06-05 19:41
>If the BLE speakers/headphones are paired before I launch the app, everything works as intended with no issues but it doesn’t work while app is running with AVAudioSessionCategoryPlayAndRecord category.
(it's OK with Playback-only categories)

The [Apple docs on the A2DP option](https://developer.apple.com/documentation/avfaudio/avaudiosessioncategoryoptions/avaudiosessioncategoryoptionallowbluetootha2dp)state:

>The system automatically routes to A2DP ports if you configure an app’s audio session to use the AVAudioSessionCategoryAmbient, AVAudioSessionCategorySoloAmbient, or AVAudioSessionCategoryPlayback categories

So for the playback category, you shouldn't need to set the option. In fact, PdAudioController does not use it unless the category is PlayAndRecord as suggested by the Apple Docs as well:

>Starting with iOS 10.0, apps using the AVAudioSessionCategoryPlayAndRecord category may also allow routing output to paired Bluetooth A2DP devices. To enable this behavior, pass this category option when setting your audio session’s category.

>~~~
>pdAudioController.configurePlayback(withSampleRate: Int32(sampleRate), numberChannels: >Int32(inputChannels + outputChannels), inputEnabled: true, mixingEnabled: false)
>pdAudioController.allowBluetoothA2DP = true
>~~~

You should try setting `allowBluetoothA2DP` *before* setting the playback category.

>Perharps you can allow to set the mode or category in the public API of PdAudioController. (mode: >AVAudioSessionModeVideoRecording)

You can do this yourself by subclassing PdAudioController and implementing the appropriate category options getter:

https://github.com/libpd/libpd/blob/master/objc/PdAudioController.h#L198

**Comment by lwinged** [comment] 2021-06-06 08:39
Hello @danomatika,

Thank you for your answer, 

But I don’t understand why you said :

> You can do this yourself by subclassing PdAudioController and implementing the appropriate category options getter:
> https://github.com/libpd/libpd/blob/master/objc/PdAudioController.h#L198

because AVAudioSession.CategoryOptions != AVAudioSession.Mode

What was your idea about that ?

I need to use AVAudioSession.Mode.videoRecording like the  guy said 

https://stackoverflow.com/questions/50789276/avaudiosession-not-working-on-certain-bluetooth-devices%E2%80%A8

It works. That’s why I asked to open the method configureSessionWithCategory and add the Mode in parameter. or something like that to avoid use AVAudioSession out of the PdAudioController.

I’m sorry, perharps I don’t understand your idea.

I (quickly) did something like this : (It works)

```
class MyPdAudioController: PdAudioController {
    
    override class func setSessionOptions(_ options: AVAudioSession.CategoryOptions) -> Bool {
        let session = AVAudioSession.sharedInstance()
        
        if session.category == .playAndRecord {
            do {
                try session.setCategory(session.category, mode: .videoRecording, options: options)
                return true
            } catch {
                return false
            }
        }
        return super.setSessionOptions(options)
    }
} 
```
```
// Call 
 if enableRecording { // for playAndRecord
       pdAudioController.allowBluetoothA2DP = true
   }
        let pdAudioStatus = pdAudioController.configurePlayback(withSampleRate: Int32(sampleRate), numberChannels: Int32(inputChannels + outputChannels), inputEnabled: enableRecording, mixingEnabled: false)
        MyPdAudioController.setSessionOptions(pdAudioController.currentCategoryOptions())
        return pdAudioStatus != PdAudioError

```
Thank you :)

**Comment by danomatika** [comment] 2021-06-06 10:12
Ok, sorry. I misread "mode" as "option" yesterday and didn't look further. Setting the audio session mode after configuring *should* work but perhaps it doesn't you note. The controller sets the category options this way: first category, then options.

In any case, I've made a `feature/audio-controller-mode` branch which adds a mode property which works similar to the category options BOOL properties: whatever is set there is used when configuring. I decided not to do anything further such as try to figure out which mode to apply when as this is more of an override of the system default and it's a bit more specific to application use cases.

As you suggest, it should work like this:

```swift
if enableRecording { // for playAndRecord
    pdAudioController.allowBluetoothA2DP = true
    // workaround which forces video recording mode to ensure BLE devices actually use A2DP...
    pdAudioController.mode = AVAudioSession.Mode.videoRecording
}
pdAudioController.configurePlayback(withSampleRate: Int32(sampleRate), numberChannels: Int32(inputChannels + outputChannels), inputEnabled: enableRecording, mixingEnabled: false)
```

There is also a new "setSessionMode" static helper.

Please test this both *with* setting the mode and *without* setting the mode, ie. only `allowBluetoothA2DP`. I changed internal session configuration to set category, mode, & options all at once and I wonder if that will help the underlying issue.

**Comment by danomatika** [comment] 2021-06-06 10:15
Also, in looking again the SO link: https://stackoverflow.com/questions/50789276/avaudiosession-not-working-on-certain-bluetooth-devices%E2%80%A8

I'm not sure if the videoRecording mode is what makes it work for them. I think that's just the mode they are using for their application and not necessarily the actual fix for the problem which is more likely to do with setting the category options *after* the category as opposed to together at once.

**Comment by lwinged** [comment] 2021-06-06 10:59
I tried on `feature/audio-controller-mode` branch

```
if enableRecording { // for playAndRecord
    pdAudioController.allowBluetoothA2DP = true
}
pdAudioController.configurePlayback(withSampleRate: Int32(sampleRate), numberChannels: Int32(inputChannels + outputChannels), inputEnabled: enableRecording, mixingEnabled: false) 

```

KO it doesn't work

But with the mode videoRecording it works
```
if enableRecording { // for playAndRecord
    pdAudioController.allowBluetoothA2DP = true
    pdAudioController.mode = AVAudioSession.Mode.videoRecording.rawValue as NSString
}
pdAudioController.configurePlayback(withSampleRate: Int32(sampleRate), numberChannels: Int32(inputChannels + outputChannels), inputEnabled: enableRecording, mixingEnabled: false) 
```

I think videoRecording mode fix this issue. 

The guy from this link: [https://stackoverflow.com/questions/50789276/avaudiosession-not-working-on-certain-bluetooth-devices%E2%80%A8](https://stackoverflow.com/questions/50789276/avaudiosession-not-working-on-certain-bluetooth-devices%E2%80%A8
)

Says : 

> If the playback is on a speaker which uses A2DP, considering setting the session like this:


```
let audioSession = AVAudioSession.sharedInstance()
do {
      try audioSession.setCategory(AVAudioSessionCategoryPlayAndRecord, 
           mode: AVAudioSessionModeVideoRecording, // HERE
           options: [.defaultToSpeaker, .allowAirPlay, .allowBluetoothA2DP])
      try audioSession.setActive(true)
} catch let error {
      print("audioSession properties weren't set!", error)
}
```

and another guy from this link: [https://stackoverflow.com/questions/63568845/avaudiosession-does-not-automatically-connect-to-bluetooth-a2dp-audio](https://stackoverflow.com/questions/63568845/avaudiosession-does-not-automatically-connect-to-bluetooth-a2dp-audio)

Says : 

> I learned that if i set the mode to VideoRecording, iOS will change the route if I turn the bluetooth on (and I get a route change notification). Without this mode I had to allow both bluetooth, after detect one, change the category again without AllowBluetooth, just A2DP. Weird and slow solution, but worked. Now im just using videorecording mode.


Another thing, I need to do this in swift : 

`pdAudioController.mode = AVAudioSession.Mode.videoRecording.rawValue as NSString`

because I have an error with : 

`pdAudioController.mode = AVAudioSession.Mode.videoRecording ->
Error : Cannot assign value of type 'AVAudioSession.Mode' to type 'NSString'
`

**Comment by danomatika** [comment] 2021-06-06 11:17
Ok, good to have confirmation. I will put a note about this in the allowBluetoothA2DP property comments.

**Comment by danomatika** [comment] 2021-06-06 11:26
Branch is merged to `master`.

**Closed by danomatika** 2021-06-06 11:26 UTC
